# Site settings
title: Place for stuff
email: gabriel.d.mikaelsson@gmail.com
description: >
  A thing to place stuff.
url: "https://surculus12.github.io" 
name: Gabriel Mikaelsson

plugins:
  - jekyll-remote-theme

# Build settings
markdown: kramdown
remote_theme: kronik3r/daktilo
